[files]
extend-exclude = ["integration-tests/*", "CHANGELOG.md", "zhang-query/tests/golden/*", "zhang-query/tests/conformance/cases/*", "zhang-query/tests/tables/oracle.json"]

[default]
# the names of integration-test fixture directories, which tests refer to
extend-ignore-re = ["budget-sytem-syntax-and-category", "shold_handle_the_meta_for_operating_currency_in_commodity_directive"]
