use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use axum::Json;
use serde_json::json;
use thiserror::Error;
use zhang_ast::account::InvalidAccountError;
use zhang_core::ZhangError;

use crate::state::ReloadFailure;

#[derive(Error, Debug)]
pub enum ServerError {
    #[error("core error: {0}")]
    CoreError(#[from] ZhangError),

    #[error("client error: {0}")]
    ClientError(#[from] reqwest::Error),

    #[error("io error: {0}")]
    IoError(#[from] std::io::Error),

    #[error("io error: {0}")]
    StrumError(#[from] strum::ParseError),

    #[error("not found")]
    NotFound,

    /// a request value the ledger could not read back; answered with HTTP 400
    #[error("{0}")]
    InvalidInput(String),

    /// a query failed to parse, compile or run; answered with HTTP 400 and its source position
    #[error("query error: {0}")]
    QueryError(#[from] zhang_query::QueryError),

    /// a blocking task panicked or was cancelled
    #[error("background task failed: {0}")]
    TaskFailed(#[from] tokio::task::JoinError),

    /// the server ran a built-in query it does not have, a bug; answered with HTTP 500
    #[error("there is no built-in query named {0}")]
    UnknownBuiltinQuery(String),

    /// the mapping of a built-in query read a column the query does not select, a bug; answered with HTTP 500
    #[error("the built-in query {query} has no column {column}")]
    MissingColumn { query: String, column: String },

    /// the files of the ledger changed, and cannot be loaded as they are now: a write that edits the ledger as loaded
    /// writes nothing until they are fixed. Answered with HTTP 409
    #[error("the ledger cannot be loaded from its files as they are now, so nothing was written. Fix them in the file editor, then try again: {}", .0.message)]
    UnloadableLedger(ReloadFailure),

    /// the reload a request asked for failed: the ledger served is the one loaded before it, until the files are
    /// fixed. Answered with HTTP 409, as a write the files refuse is
    #[error("the ledger failed to reload, so the version loaded before is still shown. Fix the files in the file editor: {}", .0.message)]
    ReloadFailed(ReloadFailure),

    /// what a request was made from is out of date: the ledger changed since. Answered with HTTP 409
    #[error("{0}")]
    Conflict(String),

    /// a document a request names is in no file. Answered with HTTP 404
    #[error("{0}")]
    NoSuchDocument(String),

    /// a file of the ledger a request names is not there. Answered with HTTP 404
    #[error("there is no file {0} in the ledger's directory")]
    NoSuchFile(String),

    /// a document a request names is outside the ledger's directory, which is all that is served. Answered with
    /// HTTP 403
    #[error("{0}")]
    OutsideLedger(String),

    /// a transaction a request names by its id is not in the ledger. Answered with HTTP 404
    #[error("there is no transaction {0} in the ledger: the journal it was picked from is out of date, or it was removed. Reopen the journal, and try again")]
    NoSuchTransaction(uuid::Uuid),

    /// a transaction a request would edit is in no file of the ledger: a plugin made it. Answered with HTTP 400
    #[error("this transaction ({0}) was generated by a plugin and can't be edited: it is in no file of the ledger")]
    PluginTransaction(String),
}

impl From<InvalidAccountError> for ServerError {
    fn from(error: InvalidAccountError) -> Self {
        Self::InvalidInput(error.to_string())
    }
}

impl IntoResponse for ServerError {
    fn into_response(self) -> Response {
        if let ServerError::QueryError(error) = self {
            // the query error body is exactly `{message, line, column}`
            return (StatusCode::BAD_REQUEST, Json(crate::response::QueryErrorEntity::from(error))).into_response();
        }
        let message = match &self {
            // nothing was written: the file changed since the ledger was loaded, or the storage refused the access
            ServerError::CoreError(
                error @ (ZhangError::FileChanged(_) | ZhangError::ReadRefused(_) | ZhangError::WriteRefused(_) | ZhangError::InvalidUtf8 { .. }),
            ) => error.to_string(),
            other => other.to_string(),
        };

        let status = match self {
            ServerError::NotFound | ServerError::NoSuchTransaction(_) | ServerError::NoSuchDocument(_) | ServerError::NoSuchFile(_) => StatusCode::NOT_FOUND,
            // the storage refused the access, whatever the storage and whichever route met it
            ServerError::OutsideLedger(_) | ServerError::CoreError(ZhangError::ReadRefused(_) | ZhangError::WriteRefused(_)) => StatusCode::FORBIDDEN,
            ServerError::InvalidInput(_) | ServerError::PluginTransaction(_) => StatusCode::BAD_REQUEST,
            ServerError::CoreError(ZhangError::FileChanged(_)) | ServerError::UnloadableLedger(_) | ServerError::ReloadFailed(_) | ServerError::Conflict(_) => {
                StatusCode::CONFLICT
            }
            // a file that is not UTF-8 text, which the editor cannot show, nor a write edit
            ServerError::CoreError(ZhangError::InvalidUtf8 { .. }) => StatusCode::UNSUPPORTED_MEDIA_TYPE,
            _ => StatusCode::INTERNAL_SERVER_ERROR,
        };

        error_response(status, message)
    }
}

/// The one body of an API error, `{"message": …}`, with `status`: every error the API answers has it, those of the
/// server, of authentication, of the router plugins' routing and of the extractors alike. A query error adds where in
/// the query it is (`QueryErrorEntity`)
pub fn error_response(status: StatusCode, message: impl Into<String>) -> Response {
    (status, Json(json!({ "message": message.into() }))).into_response()
}

/// the routes of the router plugins, whose answers are the plugins' own
const PLUGIN_ROUTES: &str = "/api/plugins/";

/// the most of a rejection's text read into its message
const MAX_REJECTION_BYTES: usize = 64 * 1024;

/// Middleware giving the rejections of axum's extractors the one body of an API error ([`error_response`]): a body
/// that is not the JSON a route takes, a path or a query string that does not read, or an upload that cannot be read
/// is answered by axum with its status and a `text/plain` reason, which becomes the message. What a router plugin
/// answers is its own, and stays as it is
pub async fn json_rejections(request: axum::extract::Request, next: axum::middleware::Next) -> Response {
    let from_plugin = request.uri().path().starts_with(PLUGIN_ROUTES);
    let response = next.run(request).await;
    let status = response.status();
    let plain_text = response
        .headers()
        .get(axum::http::header::CONTENT_TYPE)
        .and_then(|it| it.to_str().ok())
        .is_some_and(|it| it.starts_with("text/plain"));
    if from_plugin || !plain_text || !(status.is_client_error() || status.is_server_error()) {
        return response;
    }
    let reason = axum::body::to_bytes(response.into_body(), MAX_REJECTION_BYTES).await.unwrap_or_default();
    error_response(status, String::from_utf8_lossy(&reason).trim())
}

#[cfg(test)]
mod test {
    use axum::http::StatusCode;
    use axum::response::IntoResponse;
    use serde_json::json;

    use crate::error::ServerError;

    #[tokio::test]
    async fn query_errors_are_bad_requests_with_exactly_message_line_and_column() {
        let error = zhang_query::Query::compile("SELECT * WHERE payee = '午餐' AND x ~")
            .err()
            .expect("a syntax error");
        let response = ServerError::from(error).into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX).await.unwrap();
        let body: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(body, json!({"message": "expected an expression, found end of query", "line": 1, "column": 36}));
    }

    #[tokio::test]
    async fn query_errors_without_position_have_null_line_and_column() {
        let error = zhang_query::QueryError::new(zhang_query::QueryErrorKind::Eval, "boom");
        let response = ServerError::from(error).into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX).await.unwrap();
        let body: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(body, json!({"message": "boom", "line": null, "column": null}));
    }
}
