use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use axum::Json;
use serde_json::json;
use thiserror::Error;
use zhang_ast::account::InvalidAccountError;
use zhang_core::ZhangError;

#[derive(Error, Debug)]
pub enum ServerError {
    #[error("core error: {0}")]
    CoreError(#[from] ZhangError),

    #[error("client error: {0}")]
    ClientError(#[from] reqwest::Error),

    #[error("io error: {0}")]
    IoError(#[from] std::io::Error),

    #[error("io error: {0}")]
    StrumError(#[from] strum::ParseError),

    #[error("not found")]
    NotFound,

    #[error("bad request")]
    BadRequest,

    /// a request value the ledger could not read back; answered with HTTP 400
    #[error("{0}")]
    InvalidInput(String),

    /// a query failed to parse, compile or run; answered with HTTP 400 and its source position
    #[error("query error: {0}")]
    QueryError(#[from] zhang_query::QueryError),

    /// a blocking task panicked or was cancelled
    #[error("background task failed: {0}")]
    TaskFailed(#[from] tokio::task::JoinError),

    /// the server ran a built-in query it does not have, a bug; answered with HTTP 500
    #[error("there is no built-in query named {0}")]
    UnknownBuiltinQuery(String),

    /// the files of the ledger changed, and cannot be loaded as they are now: a write that edits the ledger as loaded
    /// writes nothing until they are fixed. Answered with HTTP 409
    #[error("the ledger cannot be loaded from its files as they are now, so nothing was written. Fix them in the file editor, then try again: {0}")]
    UnloadableLedger(ZhangError),

    /// what a request was made from is out of date: the ledger changed since. Answered with HTTP 409
    #[error("{0}")]
    Conflict(String),

    /// a document a request names is in no file. Answered with HTTP 404
    #[error("{0}")]
    NoSuchDocument(String),

    /// a document a request names is outside the ledger's directory, which is all that is served. Answered with
    /// HTTP 403
    #[error("{0}")]
    OutsideLedger(String),

    /// a transaction a request names by its id is not in the ledger. Answered with HTTP 404
    #[error("there is no transaction {0} in the ledger: the journal it was picked from is out of date, or it was removed. Reopen the journal, and try again")]
    NoSuchTransaction(uuid::Uuid),

    /// a transaction a request would edit is in no file of the ledger: a plugin made it. Answered with HTTP 400
    #[error("this transaction ({0}) was generated by a plugin and can't be edited: it is in no file of the ledger")]
    PluginTransaction(String),
}

impl From<InvalidAccountError> for ServerError {
    fn from(_value: InvalidAccountError) -> Self {
        Self::CoreError(ZhangError::InvalidAccount)
    }
}

impl IntoResponse for ServerError {
    fn into_response(self) -> Response {
        if let ServerError::QueryError(error) = self {
            // the query error body is exactly `{message, line, column}`
            return (StatusCode::BAD_REQUEST, Json(crate::response::QueryErrorEntity::from(error))).into_response();
        }
        let message = match &self {
            // nothing was written: the file changed since the ledger was loaded
            ServerError::CoreError(error @ (ZhangError::FileChanged(_) | ZhangError::ReadRefused(_))) => error.to_string(),
            other => other.to_string(),
        };
        let payload = json!({
            "message": message,
            "origin": "with_rejection"
        });

        let status = match self {
            ServerError::NotFound | ServerError::NoSuchTransaction(_) | ServerError::NoSuchDocument(_) => StatusCode::NOT_FOUND,
            ServerError::OutsideLedger(_) | ServerError::CoreError(ZhangError::ReadRefused(_)) => StatusCode::FORBIDDEN,
            ServerError::BadRequest | ServerError::InvalidInput(_) | ServerError::PluginTransaction(_) => StatusCode::BAD_REQUEST,
            ServerError::CoreError(ZhangError::FileChanged(_)) | ServerError::UnloadableLedger(_) | ServerError::Conflict(_) => StatusCode::CONFLICT,
            _ => StatusCode::INTERNAL_SERVER_ERROR,
        };

        (status, Json(payload)).into_response()
    }
}

#[cfg(test)]
mod test {
    use axum::http::StatusCode;
    use axum::response::IntoResponse;
    use serde_json::json;

    use crate::error::ServerError;

    #[tokio::test]
    async fn query_errors_are_bad_requests_with_exactly_message_line_and_column() {
        let error = zhang_query::Query::compile("SELECT * WHERE payee = '午餐' AND x ~")
            .err()
            .expect("a syntax error");
        let response = ServerError::from(error).into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX).await.unwrap();
        let body: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(body, json!({"message": "expected an expression, found end of query", "line": 1, "column": 36}));
    }

    #[tokio::test]
    async fn query_errors_without_position_have_null_line_and_column() {
        let error = zhang_query::QueryError::new(zhang_query::QueryErrorKind::Eval, "boom");
        let response = ServerError::from(error).into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let body = axum::body::to_bytes(response.into_body(), usize::MAX).await.unwrap();
        let body: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(body, json!({"message": "boom", "line": null, "column": null}));
    }
}
