/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/accounts': {
    /** Get Account List */
    get: operations['get_account_list'];
  };
  '/api/accounts/batch-balances': {
    /** Create Batch Account Balances */
    post: operations['create_batch_account_balances'];
  };
  '/api/accounts/{account_name}': {
    /** Get Account Info */
    get: operations['get_account_info'];
  };
  '/api/accounts/{account_name}/balances': {
    /** Get Account Balance Data */
    get: operations['get_account_balance_data'];
    /** Create Account Balance */
    post: operations['create_account_balance'];
  };
  '/api/accounts/{account_name}/documents': {
    /** Get Account Documents */
    get: operations['get_account_documents'];
    /** Upload Account Document */
    post: operations['upload_account_document'];
  };
  '/api/accounts/{account_name}/journals': {
    /** Get Account Journals */
    get: operations['get_account_journals'];
  };
  '/api/auth/login': {
    /**
     * Auth Login
     * @description Exchanges the `ZHANG_AUTH` credential for a session cookie.
     */
    post: operations['auth_login'];
  };
  '/api/auth/logout': {
    /**
     * Auth Logout
     * @description Ends the session by clearing its cookie.
     */
    post: operations['auth_logout'];
  };
  '/api/auth/passkey/login/finish': {
    /**
     * Passkey Login Finish
     * @description Finishes a passkey login and signs the caller in.
     */
    post: operations['passkey_login_finish'];
  };
  '/api/auth/passkey/login/start': {
    /**
     * Passkey Login Start
     * @description Starts a passkey login, allowing every registered passkey.
     */
    post: operations['passkey_login_start'];
  };
  '/api/auth/passkey/register/finish': {
    /**
     * Passkey Register Finish
     * @description Finishes registering a passkey and stores it. A caller without a session (registering with
     * the secret) is signed in with the new passkey; a signed-in caller keeps their session.
     */
    post: operations['passkey_register_finish'];
  };
  '/api/auth/passkey/register/start': {
    /**
     * Passkey Register Start
     * @description Starts registering a passkey; needs a session or the `ZHANG_PASSKEY` secret.
     */
    post: operations['passkey_register_start'];
  };
  '/api/auth/passkeys': {
    /**
     * Get Passkeys
     * @description The registered passkeys; needs a session.
     */
    get: operations['get_passkeys'];
  };
  '/api/auth/passkeys/{passkey_id}': {
    /**
     * Delete Passkey
     * @description Removes a passkey (and ends its sessions); needs a session. The last passkey stays while
     * password login is disabled.
     */
    delete: operations['delete_passkey'];
  };
  '/api/auth/status': {
    /**
     * Get Auth Status
     * @description Whether authentication is enabled, which methods, and who the caller is.
     */
    get: operations['get_auth_status'];
  };
  '/api/budgets': {
    /** Get Budget List */
    get: operations['get_budget_list'];
  };
  '/api/budgets/{budget_name}': {
    /** Get Budget Info */
    get: operations['get_budget_info'];
  };
  '/api/budgets/{budget_name}/interval/{year}/{month}': {
    /** Get Budget Interval Detail */
    get: operations['get_budget_interval_detail'];
  };
  '/api/commodities': {
    /** Get All Commodities */
    get: operations['get_all_commodities'];
  };
  '/api/commodities/{commodity_name}': {
    /** Get Single Commodity */
    get: operations['get_single_commodity'];
  };
  '/api/documents': {
    /** Get Documents */
    get: operations['get_documents'];
  };
  '/api/errors': {
    /** Get Errors */
    get: operations['get_errors'];
  };
  '/api/files': {
    /** Get Files */
    get: operations['get_files'];
  };
  '/api/files/{file_path}': {
    /** Get File Content */
    get: operations['get_file_content'];
    /** Update File Content */
    put: operations['update_file_content'];
  };
  '/api/for-new-transaction': {
    /** Get Info For New Transactions */
    get: operations['get_info_for_new_transactions'];
  };
  '/api/info': {
    /** Get Basic Info */
    get: operations['get_basic_info'];
  };
  '/api/journals': {
    /**
     * Get Journals
     * @description The journal: the transactions and the balance assertions, newest first. An assertion is listed in its place
     * among the transactions; it books nothing.
     */
    get: operations['get_journals'];
  };
  '/api/options': {
    /** Get All Options */
    get: operations['get_all_options'];
  };
  '/api/plugins': {
    /**
     * Plugin List
     * @description The loaded plugins in declaration order, which is the order they run in. A router plugin
     * also lists the route it serves.
     */
    get: operations['plugin_list'];
  };
  '/api/query': {
    /**
     * Run Query
     * @description Run a BQL-compatible query over the ledger.
     *
     * Query errors are answered with HTTP 400 and `{"message", "line", "column"}`.
     */
    post: operations['run_query'];
  };
  '/api/query/csv': {
    /**
     * Run Query Csv
     * @description Run a BQL-compatible query and download the result as CSV (`query.csv`).
     *
     * Amount, position and inventory columns are split into one numeric column per currency,
     * named like `balance (USD)`, as beanquery's numberify does. Query errors are answered
     * with HTTP 400 and `{"message", "line", "column"}`, as in `POST /api/query`.
     */
    post: operations['run_query_csv'];
  };
  '/api/query/saved': {
    /**
     * Get Saved Queries
     * @description The queries saved in the ledger by `query` directives, in ledger order (by date, then
     * source order). Queries sharing a name are all listed.
     *
     * Each query is compiled to report whether it is `valid` with the current engine; an
     * invalid one is still listed, with its `error`.
     */
    get: operations['get_saved_queries'];
  };
  '/api/query/schema': {
    /**
     * Get Query Schema
     * @description The columns and functions available to queries.
     */
    get: operations['get_query_schema'];
  };
  '/api/reload': {
    /** Reload */
    post: operations['reload'];
  };
  '/api/statistic/graph': {
    /** Get Statistic Graph */
    get: operations['get_statistic_graph'];
  };
  '/api/statistic/summary': {
    /** Get Statistic Summary */
    get: operations['get_statistic_summary'];
  };
  '/api/statistic/{account_type}': {
    /** Get Statistic Rank Detail By Account Type */
    get: operations['get_statistic_rank_detail_by_account_type'];
  };
  '/api/transactions': {
    /** Create New Transaction */
    post: operations['create_new_transaction'];
  };
  '/api/transactions/{transaction_id}': {
    /** Update Single Transaction */
    put: operations['update_single_transaction'];
  };
  '/api/transactions/{transaction_id}/documents': {
    /** Upload Transaction Document */
    post: operations['upload_transaction_document'];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Get Account List */
  get_account_list: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              alias?: string | null;
              /** @description the account's own balance, that of its own postings */
              amount: {
                calculated: {
                  commodity: string;
                  number: string;
                };
                detail: {
                  [key: string]: string;
                };
              };
              /**
               * @description the balance a balance assertion on the account is checked against, per currency: that of the account
               * and all its sub-accounts
               */
              balance_with_sub_accounts: {
                [key: string]: string;
              };
              /** @description whether the account has sub-accounts, whose balances `balance_with_sub_accounts` includes */
              has_sub_accounts: boolean;
              name: string;
              /** @enum {string} */
              status: 'Open' | 'Close';
            }[];
          };
        };
      };
    };
  };
  /** Create Batch Account Balances */
  create_batch_account_balances: {
    requestBody: {
      content: {
        'application/json': (
          | {
              account_name: string;
              amount: {
                commodity: string;
                number: string;
              };
              /** @enum {string} */
              type: 'Check';
            }
          | {
              account_name: string;
              amount: {
                commodity: string;
                number: string;
              };
              pad: string;
              /** @enum {string} */
              type: 'Pad';
            }
        )[];
      };
    };
    responses: {
      /** @description no content */
      204: {
        content: never;
      };
    };
  };
  /** Get Account Info */
  get_account_info: {
    parameters: {
      path: {
        account_name: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              alias?: string | null;
              /** @description the account's own balance, that of its own postings */
              amount: {
                calculated: {
                  commodity: string;
                  number: string;
                };
                detail: {
                  [key: string]: string;
                };
              };
              /**
               * @description the balance a balance assertion on the account is checked against, per currency: that of the account
               * and all its sub-accounts
               */
              balance_with_sub_accounts: {
                [key: string]: string;
              };
              /** Format: date-time */
              date: string;
              /** @description whether the account has sub-accounts, whose balances `balance_with_sub_accounts` includes */
              has_sub_accounts: boolean;
              name: string;
              'r#type': string;
              /** @enum {string} */
              status: 'Open' | 'Close';
            };
          };
        };
      };
    };
  };
  /** Get Account Balance Data */
  get_account_balance_data: {
    parameters: {
      path: {
        account_name: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              balance: {
                [key: string]: {
                  balance: {
                    commodity: string;
                    number: string;
                  };
                  /** Format: date */
                  date: string;
                }[];
              };
            };
          };
        };
      };
    };
  };
  /** Create Account Balance */
  create_account_balance: {
    parameters: {
      path: {
        account_name: string;
      };
    };
    requestBody: {
      content: {
        'application/json':
          | {
              amount: {
                commodity: string;
                number: string;
              };
              /** @enum {string} */
              type: 'Check';
            }
          | {
              amount: {
                commodity: string;
                number: string;
              };
              pad: string;
              /** @enum {string} */
              type: 'Pad';
            };
      };
    };
    responses: {
      /** @description no content */
      204: {
        content: never;
      };
    };
  };
  /** Get Account Documents */
  get_account_documents: {
    parameters: {
      path: {
        account_name: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              account?: string | null;
              /** Format: date-time */
              datetime: string;
              extension?: string | null;
              filename: string;
              path: string;
              trx_id?: string | null;
            }[];
          };
        };
      };
    };
  };
  /** Upload Account Document */
  upload_account_document: {
    parameters: {
      path: {
        account_name: string;
      };
    };
    /** @description Multipart form data */
    requestBody: {
      content: {
        'multipart/form-data': unknown;
      };
    };
    responses: {
      /** @description no content */
      204: {
        content: never;
      };
    };
  };
  /** Get Account Journals */
  get_account_journals: {
    parameters: {
      path: {
        account_name: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              account: string;
              /** @description the account's own balance after the row, that of its own postings, on every row */
              account_after: {
                commodity: string;
                number: string;
              };
              /** @description for the row of a balance assertion: the asserted amount; null for a posting */
              asserted?: {
                commodity: string;
                number: string;
              } | null;
              /**
               * @description for the row of a balance assertion: the balance it was checked against, that of the account and
               * all its sub-accounts; null for a posting
               */
              checked_balance?: {
                commodity: string;
                number: string;
              } | null;
              /** Format: date-time */
              datetime: string;
              /** @description what the row adds to the account; zero for a balance assertion, which changes no balance */
              inferred_unit: {
                commodity: string;
                number: string;
              };
              narration?: string | null;
              /** @description for the row of a balance assertion: whether it held, within its tolerance; null for a posting */
              passed?: boolean | null;
              payee?: string | null;
              timestamp: number;
              trx_id: string;
            }[];
          };
        };
      };
    };
  };
  /**
   * Auth Login
   * @description Exchanges the `ZHANG_AUTH` credential for a session cookie.
   */
  auth_login: {
    requestBody: {
      content: {
        'application/json': {
          password: string;
          username: string;
        };
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /** @description whether the caller can use the API (always true when authentication is disabled) */
              authenticated: boolean;
              /** @description whether any authentication method is enabled */
              enabled: boolean;
              methods: {
                /** @description passkeys, `ZHANG_PASSKEY` */
                passkey: boolean;
                /** @description username and password, `ZHANG_AUTH` */
                password: boolean;
              };
              /** @description whether at least one passkey is registered */
              passkey_registered: boolean;
              /** @description title of ledger */
              title?: string | null;
              /** @description who the caller is signed in as */
              user?: string | null;
            };
          };
        };
      };
    };
  };
  /**
   * Auth Logout
   * @description Ends the session by clearing its cookie.
   */
  auth_logout: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /** @description whether the caller can use the API (always true when authentication is disabled) */
              authenticated: boolean;
              /** @description whether any authentication method is enabled */
              enabled: boolean;
              methods: {
                /** @description passkeys, `ZHANG_PASSKEY` */
                passkey: boolean;
                /** @description username and password, `ZHANG_AUTH` */
                password: boolean;
              };
              /** @description whether at least one passkey is registered */
              passkey_registered: boolean;
              /** @description title of ledger */
              title?: string | null;
              /** @description who the caller is signed in as */
              user?: string | null;
            };
          };
        };
      };
    };
  };
  /**
   * Passkey Login Finish
   * @description Finishes a passkey login and signs the caller in.
   */
  passkey_login_finish: {
    requestBody: {
      content: {
        'application/json': {
          /**
           * Format: json
           * @description the `PublicKeyCredential` of `navigator.credentials.get`
           */
          credential: Record<string, never>;
          state_id: string;
        };
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /** @description whether the caller can use the API (always true when authentication is disabled) */
              authenticated: boolean;
              /** @description whether any authentication method is enabled */
              enabled: boolean;
              methods: {
                /** @description passkeys, `ZHANG_PASSKEY` */
                passkey: boolean;
                /** @description username and password, `ZHANG_AUTH` */
                password: boolean;
              };
              /** @description whether at least one passkey is registered */
              passkey_registered: boolean;
              /** @description title of ledger */
              title?: string | null;
              /** @description who the caller is signed in as */
              user?: string | null;
            };
          };
        };
      };
    };
  };
  /**
   * Passkey Login Start
   * @description Starts a passkey login, allowing every registered passkey.
   */
  passkey_login_start: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /**
               * Format: json
               * @description the options to pass to `navigator.credentials.create` / `navigator.credentials.get`
               */
              options: Record<string, never>;
              /** @description identifies the ceremony when finishing it */
              state_id: string;
            };
          };
        };
      };
    };
  };
  /**
   * Passkey Register Finish
   * @description Finishes registering a passkey and stores it. A caller without a session (registering with
   * the secret) is signed in with the new passkey; a signed-in caller keeps their session.
   */
  passkey_register_finish: {
    requestBody: {
      content: {
        'application/json': {
          /**
           * Format: json
           * @description the `RegisterPublicKeyCredential` of `navigator.credentials.create`
           */
          credential: Record<string, never>;
          /** @description the name of the new passkey, overriding the one given when starting */
          name?: string | null;
          state_id: string;
        };
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /** @description whether the caller can use the API (always true when authentication is disabled) */
              authenticated: boolean;
              /** @description whether any authentication method is enabled */
              enabled: boolean;
              methods: {
                /** @description passkeys, `ZHANG_PASSKEY` */
                passkey: boolean;
                /** @description username and password, `ZHANG_AUTH` */
                password: boolean;
              };
              /** @description whether at least one passkey is registered */
              passkey_registered: boolean;
              /** @description title of ledger */
              title?: string | null;
              /** @description who the caller is signed in as */
              user?: string | null;
            };
          };
        };
      };
    };
  };
  /**
   * Passkey Register Start
   * @description Starts registering a passkey; needs a session or the `ZHANG_PASSKEY` secret.
   */
  passkey_register_start: {
    requestBody: {
      content: {
        'application/json': {
          /** @description the name of the new passkey */
          name?: string | null;
          /** @description the `ZHANG_PASSKEY` secret, needed when the caller has no session */
          secret?: string | null;
        };
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /**
               * Format: json
               * @description the options to pass to `navigator.credentials.create` / `navigator.credentials.get`
               */
              options: Record<string, never>;
              /** @description identifies the ceremony when finishing it */
              state_id: string;
            };
          };
        };
      };
    };
  };
  /**
   * Get Passkeys
   * @description The registered passkeys; needs a session.
   */
  get_passkeys: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              created_at: string;
              id: string;
              name: string;
            }[];
          };
        };
      };
    };
  };
  /**
   * Delete Passkey
   * @description Removes a passkey (and ends its sessions); needs a session. The last passkey stays while
   * password login is disabled.
   */
  delete_passkey: {
    parameters: {
      path: {
        passkey_id: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              created_at: string;
              id: string;
              name: string;
            }[];
          };
        };
      };
    };
  };
  /**
   * Get Auth Status
   * @description Whether authentication is enabled, which methods, and who the caller is.
   */
  get_auth_status: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /** @description whether the caller can use the API (always true when authentication is disabled) */
              authenticated: boolean;
              /** @description whether any authentication method is enabled */
              enabled: boolean;
              methods: {
                /** @description passkeys, `ZHANG_PASSKEY` */
                passkey: boolean;
                /** @description username and password, `ZHANG_AUTH` */
                password: boolean;
              };
              /** @description whether at least one passkey is registered */
              passkey_registered: boolean;
              /** @description title of ledger */
              title?: string | null;
              /** @description who the caller is signed in as */
              user?: string | null;
            };
          };
        };
      };
    };
  };
  /** Get Budget List */
  get_budget_list: {
    parameters: {
      query?: {
        month?: number | null;
        year?: number | null;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              activity_amount: {
                commodity: string;
                number: string;
              };
              alias?: string | null;
              assigned_amount: {
                commodity: string;
                number: string;
              };
              available_amount: {
                commodity: string;
                number: string;
              };
              category?: string | null;
              closed: boolean;
              name: string;
            }[];
          };
        };
      };
    };
  };
  /** Get Budget Info */
  get_budget_info: {
    parameters: {
      query?: {
        month?: number | null;
        year?: number | null;
      };
      path: {
        budget_name: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              activity_amount: {
                commodity: string;
                number: string;
              };
              alias?: string | null;
              assigned_amount: {
                commodity: string;
                number: string;
              };
              available_amount: {
                commodity: string;
                number: string;
              };
              category?: string | null;
              closed: boolean;
              name: string;
              related_accounts: string[];
            };
          };
        };
      };
    };
  };
  /** Get Budget Interval Detail */
  get_budget_interval_detail: {
    parameters: {
      path: {
        budget_name: string;
        month: number;
        year: number;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: (
              | {
                  amount: {
                    commodity: string;
                    number: string;
                  };
                  /** @enum {string} */
                  event_type: 'AddAssignedAmount' | 'Transfer';
                  timestamp: number;
                  /** @enum {string} */
                  type: 'BudgetEvent';
                }
              | {
                  account: string;
                  /** @description the account's own balance after the row, that of its own postings, on every row */
                  account_after: {
                    commodity: string;
                    number: string;
                  };
                  /** @description for the row of a balance assertion: the asserted amount; null for a posting */
                  asserted?: {
                    commodity: string;
                    number: string;
                  } | null;
                  /**
                   * @description for the row of a balance assertion: the balance it was checked against, that of the account and
                   * all its sub-accounts; null for a posting
                   */
                  checked_balance?: {
                    commodity: string;
                    number: string;
                  } | null;
                  /** Format: date-time */
                  datetime: string;
                  /** @description what the row adds to the account; zero for a balance assertion, which changes no balance */
                  inferred_unit: {
                    commodity: string;
                    number: string;
                  };
                  narration?: string | null;
                  /** @description for the row of a balance assertion: whether it held, within its tolerance; null for a posting */
                  passed?: boolean | null;
                  payee?: string | null;
                  timestamp: number;
                  trx_id: string;
                  /** @enum {string} */
                  type: 'Posting';
                }
            )[];
          };
        };
      };
    };
  };
  /** Get All Commodities */
  get_all_commodities: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              group?: string | null;
              latest_price_amount?: string | null;
              latest_price_commodity?: string | null;
              /** Format: date-time */
              latest_price_date?: string | null;
              name: string;
              precision: number;
              prefix?: string | null;
              rounding: string;
              suffix?: string | null;
              total_amount: string;
            }[];
          };
        };
      };
    };
  };
  /** Get Single Commodity */
  get_single_commodity: {
    parameters: {
      path: {
        commodity_name: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              info: {
                group?: string | null;
                latest_price_amount?: string | null;
                latest_price_commodity?: string | null;
                /** Format: date-time */
                latest_price_date?: string | null;
                name: string;
                precision: number;
                prefix?: string | null;
                rounding: string;
                suffix?: string | null;
                total_amount: string;
              };
              lots: {
                account: string;
                /** Format: date */
                acquisition_date?: string | null;
                amount: string;
                cost?: {
                  commodity: string;
                  number: string;
                } | null;
                price?: {
                  commodity: string;
                  number: string;
                } | null;
              }[];
              prices: {
                amount: {
                  commodity: string;
                  number: string;
                };
                /** Format: date-time */
                datetime: string;
              }[];
            };
          };
        };
      };
    };
  };
  /** Get Documents */
  get_documents: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              account?: string | null;
              /** Format: date-time */
              datetime: string;
              extension?: string | null;
              filename: string;
              path: string;
              trx_id?: string | null;
            }[];
          };
        };
      };
    };
  };
  /** Get Errors */
  get_errors: {
    parameters: {
      query?: {
        page?: number | null;
        size?: number | null;
        keyword?: string | null;
        tags?: string[] | null;
        links?: string[] | null;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              current_page: number;
              page_size: number;
              records: {
                /** @enum {string} */
                error_type:
                  | 'UnbalancedTransaction'
                  | 'TransactionCannotInferTradeAmount'
                  | 'TransactionHasMultipleImplicitPosting'
                  | 'TransactionExplicitPostingHaveMultipleCommodity'
                  | 'AccountBalanceCheckError'
                  | 'AccountDoesNotExist'
                  | 'AccountClosed'
                  | 'CommodityDoesNotDefine'
                  | 'NoEnoughCommodityLot'
                  | 'CloseNonZeroAccount'
                  | 'BudgetDoesNotExist'
                  | 'DefineDuplicatedBudget'
                  | 'MultipleOperatingCurrencyDetect'
                  | 'ParseInvalidMeta'
                  | 'UnsupportedBookingMethod'
                  | 'AmbiguousLotMatch'
                  | 'PluginError';
                id: string;
                metas: {
                  [key: string]: string;
                };
                span?: {
                  content: string;
                  end: number;
                  filename?: string | null;
                  start: number;
                } | null;
              }[];
              total_count: number;
              total_page: number;
            };
          };
        };
      };
    };
  };
  /** Get Files */
  get_files: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data?: (string | null)[];
          };
        };
      };
    };
  };
  /** Get File Content */
  get_file_content: {
    parameters: {
      path: {
        file_path: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              content: string;
              path: string;
            };
          };
        };
      };
    };
  };
  /** Update File Content */
  update_file_content: {
    parameters: {
      path: {
        file_path: string;
      };
    };
    requestBody: {
      content: {
        'application/json': {
          content: string;
        };
      };
    };
    responses: {
      /** @description no content */
      204: {
        content: never;
      };
    };
  };
  /** Get Info For New Transactions */
  get_info_for_new_transactions: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              account_name: string[];
              payee: string[];
            };
          };
        };
      };
    };
  };
  /** Get Basic Info */
  get_basic_info: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /** @description docker build date of zhang accounting */
              build_date: string;
              /** @description title of ledger */
              title?: string | null;
              /** @description version of zhang accounting */
              version: string;
            };
          };
        };
      };
    };
  };
  /**
   * Get Journals
   * @description The journal: the transactions and the balance assertions, newest first. An assertion is listed in its place
   * among the transactions; it books nothing.
   */
  get_journals: {
    parameters: {
      query: {
        keyword: string | null;
        links: string[] | null;
        page: number | null;
        size: number | null;
        tags: string[] | null;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              current_page: number;
              page_size: number;
              records: (
                | {
                    /** Format: date-time */
                    datetime: string;
                    flag: string;
                    /** Format: uuid */
                    id: string;
                    is_balanced: boolean;
                    links: string[];
                    metas: {
                      key: string;
                      value: string;
                    }[];
                    narration?: string | null;
                    payee: string;
                    postings: {
                      account: string;
                      account_after: {
                        commodity: string;
                        number: string;
                      };
                      account_before: {
                        commodity: string;
                        number: string;
                      };
                      cost?: {
                        commodity: string;
                        number: string;
                      } | null;
                      inferred_unit: {
                        commodity: string;
                        number: string;
                      };
                      /** @description metadata of the posting, sorted by key */
                      metas: {
                        key: string;
                        value: string;
                      }[];
                      unit?: {
                        commodity: string;
                        number: string;
                      } | null;
                    }[];
                    sequence: number;
                    tags: string[];
                    /** @enum {string} */
                    type: 'Transaction';
                  }
                | {
                    /** Format: date-time */
                    datetime: string;
                    /** Format: uuid */
                    id: string;
                    /** @description the account */
                    narration?: string | null;
                    /** @description whether the balance is within the tolerance of the asserted amount */
                    passed: boolean;
                    /** @description `Balance Check` */
                    payee: string;
                    /**
                     * @description one entry describing the check, not a posting: `account_before` is the balance it was checked against, that of the
                     * account and all its sub-accounts where the assertion stands, `account_after` the asserted amount, and `unit` and
                     * `inferred_unit` the asserted amount minus the balance
                     */
                    postings: {
                      account: string;
                      account_after: {
                        commodity: string;
                        number: string;
                      };
                      account_before: {
                        commodity: string;
                        number: string;
                      };
                      cost?: {
                        commodity: string;
                        number: string;
                      } | null;
                      inferred_unit: {
                        commodity: string;
                        number: string;
                      };
                      /** @description metadata of the posting, sorted by key */
                      metas: {
                        key: string;
                        value: string;
                      }[];
                      unit?: {
                        commodity: string;
                        number: string;
                      } | null;
                    }[];
                    sequence: number;
                    /** @description the explicit tolerance (`~`) of the assertion; null for an exact one */
                    tolerance?: string | null;
                    /** @enum {string} */
                    type: 'BalanceCheck';
                    type_: string;
                  }
                | {
                    /** Format: date-time */
                    datetime: string;
                    /** Format: uuid */
                    id: string;
                    narration?: string | null;
                    payee: string;
                    postings: {
                      account: string;
                      account_after: {
                        commodity: string;
                        number: string;
                      };
                      account_before: {
                        commodity: string;
                        number: string;
                      };
                      cost?: {
                        commodity: string;
                        number: string;
                      } | null;
                      inferred_unit: {
                        commodity: string;
                        number: string;
                      };
                      /** @description metadata of the posting, sorted by key */
                      metas: {
                        key: string;
                        value: string;
                      }[];
                      unit?: {
                        commodity: string;
                        number: string;
                      } | null;
                    }[];
                    sequence: number;
                    /** @enum {string} */
                    type: 'BalancePad';
                    type_: string;
                  }
              )[];
              total_count: number;
              total_page: number;
            };
          };
        };
      };
    };
  };
  /** Get All Options */
  get_all_options: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              key: string;
              value: string;
            }[];
          };
        };
      };
    };
  };
  /**
   * Plugin List
   * @description The loaded plugins in declaration order, which is the order they run in. A router plugin
   * also lists the route it serves.
   */
  plugin_list: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              capabilities: {
                /** @description hosts the plugin may reach over HTTP; empty means no network access */
                allowed_hosts: string[];
              };
              name: string;
              /** @description the types the plugin runs as; a declared type this zhang does not know is left out */
              plugin_type: ('Processor' | 'Mapper' | 'Router')[];
              /**
               * @description where a router plugin serves requests, `/api/plugins/{name}`; null for a plugin that is not a
               * router, and for a router whose name an earlier router plugin already serves
               */
              route: string | null;
              version: string;
            }[];
          };
        };
      };
    };
  };
  /**
   * Run Query
   * @description Run a BQL-compatible query over the ledger.
   *
   * Query errors are answered with HTTP 400 and `{"message", "line", "column"}`.
   */
  run_query: {
    requestBody: {
      content: {
        'application/json': {
          /** @description the BQL query text */
          query: string;
        };
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              columns: {
                name: string;
                /** @enum {string} */
                type: 'null' | 'bool' | 'int' | 'decimal' | 'str' | 'date' | 'set' | 'amount' | 'position' | 'inventory';
              }[];
              rows: (
                | boolean
                | number
                | string
                | string[]
                | {
                    currency: string;
                    number: string;
                  }
                | {
                    cost: {
                      currency: string;
                      date: string | null;
                      label: string | null;
                      number: string;
                    } | null;
                    units: {
                      currency: string;
                      number: string;
                    };
                  }
                | {
                    positions: {
                      cost: {
                        currency: string;
                        date: string | null;
                        label: string | null;
                        number: string;
                      } | null;
                      units: {
                        currency: string;
                        number: string;
                      };
                    }[];
                  }
                | null
              )[][];
            };
          };
        };
      };
      /** @description the query cannot be parsed, compiled or run */
      400: {
        content: {
          'application/json': {
            column: number | null;
            line: number | null;
            message: string;
          };
        };
      };
    };
  };
  /**
   * Run Query Csv
   * @description Run a BQL-compatible query and download the result as CSV (`query.csv`).
   *
   * Amount, position and inventory columns are split into one numeric column per currency,
   * named like `balance (USD)`, as beanquery's numberify does. Query errors are answered
   * with HTTP 400 and `{"message", "line", "column"}`, as in `POST /api/query`.
   */
  run_query_csv: {
    requestBody: {
      content: {
        'application/json': {
          /** @description the BQL query text */
          query: string;
        };
      };
    };
    responses: {
      /** @description the result as RFC 4180 CSV with a header row; amount, position and inventory columns are split into one numeric column per currency, named like `balance (USD)` */
      200: {
        headers: {
          /**
           * @description download as query.csv
           * @example attachment; filename="query.csv"
           */
          'Content-Disposition': string;
        };
        content: {
          'text/csv; charset=utf-8': string;
        };
      };
      /** @description the query cannot be parsed, compiled or run */
      400: {
        content: {
          'application/json': {
            column: number | null;
            line: number | null;
            message: string;
          };
        };
      };
    };
  };
  /**
   * Get Saved Queries
   * @description The queries saved in the ledger by `query` directives, in ledger order (by date, then
   * source order). Queries sharing a name are all listed.
   *
   * Each query is compiled to report whether it is `valid` with the current engine; an
   * invalid one is still listed, with its `error`.
   */
  get_saved_queries: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /**
               * Format: date
               * @description the directive's date, `YYYY-MM-DD`
               */
              date: string;
              /** @description why the query does not compile (with its position when known), `null` when valid */
              error: string | null;
              name: string;
              /** @description the query text, verbatim */
              query: string;
              /**
               * @description whether the query compiles with the current engine; saved queries are never
               * validated at load time, so one written for a future feature is simply `false`
               */
              valid: boolean;
            }[];
          };
        };
      };
    };
  };
  /**
   * Get Query Schema
   * @description The columns and functions available to queries.
   */
  get_query_schema: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              /** @description the columns of the `postings` table, the default table */
              columns: {
                description: string;
                name: string;
                /** @enum {string} */
                type: 'null' | 'bool' | 'int' | 'decimal' | 'str' | 'date' | 'set' | 'amount' | 'position' | 'inventory';
              }[];
              functions: {
                /** @description whether this is an aggregate function (`sum`, `count`, ...) */
                aggregate: boolean;
                description: string;
                name: string;
                /** @description e.g. `root(str, int) -> str` */
                signature: string;
              }[];
              /** @description every table, `postings` first */
              tables: {
                columns: {
                  description: string;
                  name: string;
                  /** @enum {string} */
                  type: 'null' | 'bool' | 'int' | 'decimal' | 'str' | 'date' | 'set' | 'amount' | 'position' | 'inventory';
                }[];
                description: string;
                /** @description the table name, without `#` */
                name: string;
              }[];
            };
          };
        };
      };
    };
  };
  /** Reload */
  reload: {
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: string;
          };
        };
      };
    };
  };
  /** Get Statistic Graph */
  get_statistic_graph: {
    parameters: {
      query: {
        from: string;
        to: string;
        interval: 'Day' | 'Week' | 'Month';
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              balances: {
                [key: string]: {
                  calculated: {
                    commodity: string;
                    number: string;
                  };
                  detail: {
                    [key: string]: string;
                  };
                };
              };
              changes: {
                [key: string]: {
                  [key: string]: {
                    calculated: {
                      commodity: string;
                      number: string;
                    };
                    detail: {
                      [key: string]: string;
                    };
                  };
                };
              };
              /** Format: date-time */
              from: string;
              /** Format: date-time */
              to: string;
            };
          };
        };
      };
    };
  };
  /** Get Statistic Summary */
  get_statistic_summary: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              balance: {
                calculated: {
                  commodity: string;
                  number: string;
                };
                detail: {
                  [key: string]: string;
                };
              };
              expense: {
                calculated: {
                  commodity: string;
                  number: string;
                };
                detail: {
                  [key: string]: string;
                };
              };
              from: string;
              income: {
                calculated: {
                  commodity: string;
                  number: string;
                };
                detail: {
                  [key: string]: string;
                };
              };
              liability: {
                calculated: {
                  commodity: string;
                  number: string;
                };
                detail: {
                  [key: string]: string;
                };
              };
              to: string;
              transaction_number: number;
            };
          };
        };
      };
    };
  };
  /** Get Statistic Rank Detail By Account Type */
  get_statistic_rank_detail_by_account_type: {
    parameters: {
      query: {
        from: string;
        to: string;
      };
      path: {
        account_type: string;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: {
              detail: {
                account: string;
                amount: {
                  calculated: {
                    commodity: string;
                    number: string;
                  };
                  detail: {
                    [key: string]: string;
                  };
                };
              }[];
              /** Format: date-time */
              from: string;
              /** Format: date-time */
              to: string;
              top_transactions: {
                account: string;
                /** @description the account's own balance after the row, that of its own postings, on every row */
                account_after: {
                  commodity: string;
                  number: string;
                };
                /** @description for the row of a balance assertion: the asserted amount; null for a posting */
                asserted?: {
                  commodity: string;
                  number: string;
                } | null;
                /**
                 * @description for the row of a balance assertion: the balance it was checked against, that of the account and
                 * all its sub-accounts; null for a posting
                 */
                checked_balance?: {
                  commodity: string;
                  number: string;
                } | null;
                /** Format: date-time */
                datetime: string;
                /** @description what the row adds to the account; zero for a balance assertion, which changes no balance */
                inferred_unit: {
                  commodity: string;
                  number: string;
                };
                narration?: string | null;
                /** @description for the row of a balance assertion: whether it held, within its tolerance; null for a posting */
                passed?: boolean | null;
                payee?: string | null;
                timestamp: number;
                trx_id: string;
              }[];
            };
          };
        };
      };
    };
  };
  /** Create New Transaction */
  create_new_transaction: {
    requestBody: {
      content: {
        'application/json': {
          datetime: string;
          flag?: string | null;
          links: string[];
          metas: {
            key: string;
            value: string;
          }[];
          narration?: string | null;
          payee: string;
          postings: {
            account: string;
            /** @description metadata of the posting, checked like the transaction's `metas` */
            metas?:
              | {
                  key: string;
                  value: string;
                }[]
              | null;
            unit?: {
              commodity: string;
              number: string;
            } | null;
          }[];
          tags: string[];
        };
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: string;
          };
        };
      };
    };
  };
  /** Update Single Transaction */
  update_single_transaction: {
    parameters: {
      path: {
        transaction_id: string;
      };
    };
    requestBody: {
      content: {
        'application/json': {
          datetime: string;
          flag?: string | null;
          links: string[];
          metas: {
            key: string;
            value: string;
          }[];
          narration?: string | null;
          payee: string;
          postings: {
            account: string;
            /** @description metadata of the posting, checked like the transaction's `metas` */
            metas?:
              | {
                  key: string;
                  value: string;
                }[]
              | null;
            unit?: {
              commodity: string;
              number: string;
            } | null;
          }[];
          tags: string[];
        };
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data?: Record<string, never>;
          };
        };
      };
    };
  };
  /** Upload Transaction Document */
  upload_transaction_document: {
    parameters: {
      path: {
        transaction_id: string;
      };
    };
    /** @description Multipart form data */
    requestBody: {
      content: {
        'multipart/form-data': unknown;
      };
    };
    responses: {
      /** @description default return */
      200: {
        content: {
          'application/json': {
            data: string;
          };
        };
      };
    };
  };
}
