//! The beanquery oracle of `FROM #table`: `cases/tables/oracle.json`, generated by `generate.py --set
//! tables`, run through `zhang_testkit::oracle` with the conformance rules; the column names are
//! compared too, because `SELECT *` expands to a table's column list. The `#entries` count by type is
//! the conformance case `123_entries_count_by_type` (the same query over the same ledger and oracle)
//! and is not repeated here. The engine tests of the tables are in `tests/engine/tables.rs`.

use std::collections::HashMap;
use std::path::PathBuf;

use chrono::NaiveDate;
use zhang_core::ledger::Ledger;
use zhang_testkit::oracle::{assert_no_failures, load_tables, run_case, Rules};

fn today() -> NaiveDate {
    NaiveDate::from_ymd_opt(2024, 6, 30).unwrap()
}

fn ledger(name: &str) -> Ledger {
    match name {
        "fava" => zhang_testkit::ledger::fava_demo_ledger(),
        "extra" => zhang_testkit::ledger::load_ledger(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/oracle/ledgers/tables"), "main.zhang"),
        other => panic!("unknown oracle ledger {}", other),
    }
}

#[test]
fn tables_match_beanquery() {
    let mut cases = load_tables(&PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/oracle/cases/tables/oracle.json"));
    for case in &mut cases {
        case.strict_names = true;
    }
    let mut ledgers: HashMap<String, Ledger> = HashMap::new();
    let rules = Rules::on(today());
    let reports = cases
        .iter()
        .map(|case| {
            let name = case.ledger.as_deref().expect("every table case names its ledger");
            let ledger = ledgers.entry(name.to_owned()).or_insert_with(|| ledger(name));
            run_case(ledger, case, &rules, &[], &[])
        })
        .collect::<Vec<_>>();
    assert_no_failures("tables", &reports);
    assert!(cases.len() >= 30);
}
